name: Create New Tag

on:
  push:
    branches:
      - 'main'

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tag version
        id: set_version
        run: echo "::set-output name=tag::v$(date +'%Y%m%d%H%M%S')"

      - name: Create Git Tag
        run: git tag ${{ steps.set_version.outputs.tag }}
        if: success()

      - name: Push Tag to Repository
        run: git push origin ${{ steps.set_version.outputs.tag }}
        if: success()
        name: Main

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')