name: Create New Tag

on:
  push:
    branches:
      - 'main'
      - 'git-releases'

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read current version
        id: read_version
        run: echo "::set-output name=version::$(cat version.txt)"
      
      - name: Increment version
        id: increment_version
        run: |
          OLD_VERSION=${{ steps.read_version.outputs.version }}
          MAJOR=$(echo "$OLD_VERSION" | cut -d'.' -f1)
          MINOR=$(echo "$OLD_VERSION" | cut -d'.' -f2)
          PATCH=$(echo "$OLD_VERSION" | cut -d'.' -f3)
          NEW_PATCH=$((PATCH+1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
          echo "::set-output name=version::$NEW_VERSION"
          echo "$NEW_VERSION" > version.txt
      
      - name: Commit version update
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@example.com'
          git add version.txt
          git commit -m "Bump version to ${{ steps.increment_version.outputs.version }}"
          git push
      
      - name: Push Tag to Repository
        run: git push origin ${{ steps.set_version.outputs.tag }}
        if: success()
        name: Main

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')