name: Create New Tag

on:
  push:
    branches:
      - '*'

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set tag version
        id: set_version
        run: |
          if [ "${GITHUB_REF##*/}" == "main" ]; then
          #echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"
            echo "::set-output name=tag::$(cat VERION.txt')"

          else
          #  echo "::set-output name=tag::rc$(date +'%Y%m%d%H%M%S')"
            echo "::set-output name=tag::rc$(cat VERION.txt')$short_sha"
          fi

      - name: Create Git Tag
        run: git tag ${{ steps.set_version.outputs.tag }}
        if: success()

      - name: Push Tag to Repository
        run: git push origin ${{ steps.set_version.outputs.tag }}
        if: success()
