name: Terraform Lint

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt check
        run: terraform fmt -check=true

      - name: Terraform validate
        run: terraform validate

      - name: Terraform tflint
        uses: cweagans/gh-action-tflint@v1
        with:
          tf_version: '1.0.0'
